float tfxHashF(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

vec3 tfxHsv(float h, float s, float v) {
    vec3 k = abs(fract(vec3(h) + vec3(0.0, 2.0 / 3.0, 1.0 / 3.0)) * 6.0 - 3.0);
    return v * mix(vec3(1.0), clamp(k - 1.0, 0.0, 1.0), s);
}

#define TFX_SPD 1.0
#define TFX_INT 1.0

    #moj_import <tfx_blysk.fsh>
    #moj_import <tfx_neonfala.fsh>
    #moj_import <tfx_tecafala.fsh>
    #moj_import <tfx_kaskada.fsh>
    #moj_import <tfx_laser2.fsh>
    #moj_import <tfx_grzmot.fsh>
    #moj_import <tfx_obrys.fsh>
    #moj_import <tfx_neon.fsh>
    #moj_import <tfx_neon_puls.fsh>
    #moj_import <tfx_zloty_blask.fsh>
    #moj_import <tfx_galaktyka.fsh>
    #moj_import <tfx_krew.fsh>
    #moj_import <tfx_piorun.fsh>
    #moj_import <tfx_plazma.fsh>
    #moj_import <tfx_ogien.fsh>
    #moj_import <tfx_lod.fsh>
    #moj_import <tfx_diament.fsh>
    #moj_import <tfx_aurora.fsh>
    #moj_import <tfx_ocean.fsh>
    #moj_import <tfx_neon_grad.fsh>
    #moj_import <tfx_chroma.fsh>
    #moj_import <tfx_morse.fsh>
    #moj_import <tfx_radar.fsh>
    #moj_import <tfx_glow.fsh>
    #moj_import <tfx_holo.fsh>
    #moj_import <tfx_static_tv.fsh>
    #moj_import <tfx_wave.fsh>
    #moj_import <tfx_wave_big.fsh>
    #moj_import <tfx_rainbow.fsh>
    #moj_import <tfx_glitch_hard.fsh>
    #moj_import <tfx_tsunami.fsh>
    #moj_import <tfx_karuzela.fsh>
    #moj_import <tfx_tornado.fsh>
    #moj_import <tfx_bumper.fsh>
    #moj_import <tfx_pulse.fsh>
    #moj_import <tfx_heartbeat.fsh>
    #moj_import <tfx_flicker.fsh>
    #moj_import <tfx_shake.fsh>
    #moj_import <tfx_ripple.fsh>
    #moj_import <tfx_orbita.fsh>
    #moj_import <tfx_skok.fsh>
    #moj_import <tfx_sway.fsh>
    #moj_import <tfx_hopwave.fsh>
    #moj_import <tfx_wobble.fsh>
    #moj_import <tfx_spin.fsh>
    #moj_import <tfx_tremor.fsh>
    #moj_import <tfx_floaty.fsh>
    #moj_import <tfx_zigzag.fsh>
    #moj_import <tfx_spryna.fsh>
    #moj_import <tfx_szarp.fsh>
    #moj_import <tfx_tancuj.fsh>
    #moj_import <tfx_lawina.fsh>
    #moj_import <tfx_dym.fsh>
    #moj_import <tfx_neon_oddech.fsh>
    #moj_import <tfx_winda.fsh>
    #moj_import <tfx_karuzela_neon.fsh>
    #moj_import <tfx_neon_deszcz.fsh>
    #moj_import <tfx_konfetti.fsh>
    #moj_import <tfx_fala_fioletowa.fsh>
    #moj_import <tfx_fala_zlota.fsh>
    #moj_import <tfx_magnes.fsh>
    #moj_import <tfx_sznurek.fsh>
    #moj_import <tfx_fala_zielona.fsh>
    #moj_import <tfx_fala_rozowa.fsh>
    #moj_import <tfx_prad.fsh>
    #moj_import <tfx_luna.fsh>
    #moj_import <tfx_bateria.fsh>
    #moj_import <tfx_wyskok.fsh>
    #moj_import <tfx_tarcza.fsh>
    #moj_import <tfx_gwiazdki.fsh>
    #moj_import <tfx_neon_laser.fsh>
    #moj_import <tfx_wstecz.fsh>
    #moj_import <tfx_morska.fsh>
    #moj_import <tfx_karmazyn.fsh>
    #moj_import <tfx_wizja.fsh>
    #moj_import <tfx_helikopter.fsh>
    #moj_import <tfx_spirala.fsh>
    #moj_import <tfx_wibrowanie.fsh>
    #moj_import <tfx_falstart.fsh>
    #moj_import <tfx_wachlarz.fsh>
    #moj_import <tfx_deszcz_ziemi.fsh>
    #moj_import <tfx_wznoszenie.fsh>
    #moj_import <tfx_losowe_skoki.fsh>
    #moj_import <tfx_fala_wodna.fsh>
    #moj_import <tfx_zygzak_v2.fsh>
    #moj_import <tfx_metronom.fsh>
    #moj_import <tfx_drgania_muzyczne.fsh>
    #moj_import <tfx_puls_zer.fsh>
    #moj_import <tfx_wielkie_kolo.fsh>
    #moj_import <tfx_falowanie_gora.fsh>
    #moj_import <tfx_szarpacze_fale.fsh>
    #moj_import <tfx_unoszenie_fale.fsh>
    #moj_import <tfx_trzesienie_pionowe.fsh>
    #moj_import <tfx_fala_od_srodka.fsh>
    #moj_import <tfx_bungee.fsh>
    #moj_import <tfx_neon_fiolet.fsh>
    #moj_import <tfx_neon_cyjan.fsh>
    #moj_import <tfx_zloto.fsh>
    #moj_import <tfx_platyna.fsh>
    #moj_import <tfx_miedz.fsh>
    #moj_import <tfx_lawenda.fsh>
    #moj_import <tfx_szmaragd.fsh>
    #moj_import <tfx_rubin.fsh>
    #moj_import <tfx_szafir.fsh>
    #moj_import <tfx_topaz.fsh>
    #moj_import <tfx_perla.fsh>
    #moj_import <tfx_neony_tokio.fsh>
    #moj_import <tfx_retro.fsh>
    #moj_import <tfx_pixel_8bit.fsh>
    #moj_import <tfx_tlen.fsh>
    #moj_import <tfx_neon_amber.fsh>
    #moj_import <tfx_galaktyczny.fsh>
    #moj_import <tfx_tusza_neon.fsh>
    #moj_import <tfx_olo.fsh>
    #moj_import <tfx_rose_gold.fsh>
    #moj_import <tfx_helikopter_zloto.fsh>
    #moj_import <tfx_spirala_platyna.fsh>
    #moj_import <tfx_wibrowanie_miedz.fsh>
    #moj_import <tfx_falstart_lawenda.fsh>
    #moj_import <tfx_wachlarz_szmaragd.fsh>
    #moj_import <tfx_deszcz_ziemi_rubin.fsh>
    #moj_import <tfx_wznoszenie_szafir.fsh>
    #moj_import <tfx_losowe_skoki_topaz.fsh>
    #moj_import <tfx_fala_wodna_perla.fsh>
    #moj_import <tfx_zygzak_v2_neony_tokio.fsh>
    #moj_import <tfx_metronom_retro.fsh>
    #moj_import <tfx_drgania_muzyczne_pixel_8bit.fsh>
    #moj_import <tfx_puls_zer_tlen.fsh>
    #moj_import <tfx_wielkie_kolo_neon_amber.fsh>
    #moj_import <tfx_falowanie_gora_galaktyczny.fsh>
    #moj_import <tfx_szarpacze_fale_tusza_neon.fsh>
    #moj_import <tfx_unoszenie_fale_olo.fsh>
    #moj_import <tfx_trzesienie_pionowe_rose_gold.fsh>
    #moj_import <tfx_fala_od_srodka_neon_fiolet.fsh>
    #moj_import <tfx_bungee_neon_cyjan.fsh>
    #moj_import <tfx_helikopter_szmaragd.fsh>
    #moj_import <tfx_spirala_rubin.fsh>
    #moj_import <tfx_wibrowanie_szafir.fsh>
    #moj_import <tfx_falstart_topaz.fsh>
    #moj_import <tfx_wachlarz_perla.fsh>
    #moj_import <tfx_deszcz_ziemi_neony_tokio.fsh>
    #moj_import <tfx_wznoszenie_retro.fsh>
    #moj_import <tfx_losowe_skoki_pixel_8bit.fsh>
    #moj_import <tfx_fala_wodna_tlen.fsh>
    #moj_import <tfx_zygzak_v2_neon_amber.fsh>
    #moj_import <tfx_metronom_galaktyczny.fsh>
    #moj_import <tfx_drgania_muzyczne_tusza_neon.fsh>
    #moj_import <tfx_puls_zer_olo.fsh>
    #moj_import <tfx_wielkie_kolo_rose_gold.fsh>
    #moj_import <tfx_falowanie_gora_neon_fiolet.fsh>
    #moj_import <tfx_szarpacze_fale_neon_cyjan.fsh>
    #moj_import <tfx_unoszenie_fale_zloto.fsh>
    #moj_import <tfx_trzesienie_pionowe_platyna.fsh>
    #moj_import <tfx_fala_od_srodka_miedz.fsh>
    #moj_import <tfx_bungee_lawenda.fsh>
    #moj_import <tfx_kotwica.fsh>
    #moj_import <tfx_piorko.fsh>
    #moj_import <tfx_strzala.fsh>
    #moj_import <tfx_most.fsh>
    #moj_import <tfx_zegar.fsh>
    #moj_import <tfx_skakosz.fsh>
    #moj_import <tfx_fala_kot.fsh>
    #moj_import <tfx_przepylacz.fsh>
    #moj_import <tfx_wielblik.fsh>
    #moj_import <tfx_deszczyk.fsh>
    #moj_import <tfx_ptaszek.fsh>
    #moj_import <tfx_rakieta.fsh>
    #moj_import <tfx_wahadlo.fsh>
    #moj_import <tfx_plyn.fsh>
    #moj_import <tfx_bumerang.fsh>
    #moj_import <tfx_srebro.fsh>
    #moj_import <tfx_krystal.fsh>
    #moj_import <tfx_polarna.fsh>
    #moj_import <tfx_magma.fsh>
    #moj_import <tfx_mroz.fsh>
    #moj_import <tfx_pryzmat.fsh>
    #moj_import <tfx_szampan.fsh>
    #moj_import <tfx_grafit.fsh>
    #moj_import <tfx_mosiadz.fsh>
    #moj_import <tfx_karmel.fsh>
    #moj_import <tfx_wisnia.fsh>
    #moj_import <tfx_trawa.fsh>
    #moj_import <tfx_niebo.fsh>
    #moj_import <tfx_wschod.fsh>
    #moj_import <tfx_zachod.fsh>
    #moj_import <tfx_kotwica_srebro.fsh>
    #moj_import <tfx_piorko_krystal.fsh>
    #moj_import <tfx_strzala_polarna.fsh>
    #moj_import <tfx_most_magma.fsh>
    #moj_import <tfx_zegar_mroz.fsh>
    #moj_import <tfx_skakosz_pryzmat.fsh>
    #moj_import <tfx_fala_kot_szampan.fsh>
    #moj_import <tfx_przepylacz_grafit.fsh>
    #moj_import <tfx_wielblik_mosiadz.fsh>
    #moj_import <tfx_deszczyk_karmel.fsh>
    #moj_import <tfx_ptaszek_wisnia.fsh>
    #moj_import <tfx_rakieta_trawa.fsh>
    #moj_import <tfx_wahadlo_niebo.fsh>
    #moj_import <tfx_plyn_wschod.fsh>
    #moj_import <tfx_bumerang_zachod.fsh>
    #moj_import <tfx_kotwica_magma.fsh>
    #moj_import <tfx_most_krystal.fsh>
    #moj_import <tfx_piorko_polarna.fsh>
    #moj_import <tfx_skakosz_szampan.fsh>
    #moj_import <tfx_wielblik_pryzmat.fsh>
    #moj_import <tfx_matrix.fsh>
    #moj_import <tfx_haker.fsh>
    #moj_import <tfx_binarny.fsh>
    #moj_import <tfx_terminal.fsh>
    #moj_import <tfx_kod.fsh>
    #moj_import <tfx_glitch_binarny.fsh>
    #moj_import <tfx_deszcz_kodu.fsh>
    #moj_import <tfx_zerojedynka.fsh>
    #moj_import <tfx_cyber.fsh>
    #moj_import <tfx_backdoor.fsh>
    #moj_import <tfx_lampa_biala.fsh>
    #moj_import <tfx_lampa_zlota.fsh>
    #moj_import <tfx_laser_zielony.fsh>
    #moj_import <tfx_laser_fioletowy.fsh>
    #moj_import <tfx_fala2_morska.fsh>
    #moj_import <tfx_fala2_lawendowa.fsh>
    #moj_import <tfx_skaner_neon.fsh>
    #moj_import <tfx_skaner_plazmowy.fsh>
    #moj_import <tfx_gwiazdy_snieg.fsh>
    #moj_import <tfx_gwiazdy_zloto.fsh>
    #moj_import <tfx_pulsar_karmazyn.fsh>
    #moj_import <tfx_pulsar_neonowy.fsh>
    #moj_import <tfx_drganie_siebie.fsh>
    #moj_import <tfx_drganie_fali.fsh>
    #moj_import <tfx_skok_wesoly.fsh>
    #moj_import <tfx_skok_sprint.fsh>
    #moj_import <tfx_wahadlo_zegar.fsh>
    #moj_import <tfx_wahadlo_luna.fsh>
    #moj_import <tfx_wir_galaktyka.fsh>
    #moj_import <tfx_wir_ocean.fsh>
    #moj_import <tfx_kap_kropla.fsh>
    #moj_import <tfx_kap_wodny.fsh>
    #moj_import <tfx_dryf_chmura.fsh>
    #moj_import <tfx_dryf_zarny.fsh>
    #moj_import <tfx_matrix_zielony.fsh>
    #moj_import <tfx_matrix_fiolet.fsh>
