package org.bukkit;
public enum Sound {
    UI_BUTTON_CLICK, ENTITY_EXPERIENCE_ORB_PICKUP, BLOCK_NOTE_BLOCK_PLING,
    BLOCK_NOTE_BLOCK_BELL, ENTITY_VILLAGER_YES, ENTITY_VILLAGER_NO,
    ITEM_TOTEM_USE, ENTITY_ENDER_EYE_LAUNCH, BLOCK_BEACON_ACTIVATE
}
