package org.bukkit.inventory;
public enum Material {
    AIR,
    GRAY_STAINED_GLASS_PANE, BLACK_STAINED_GLASS_PANE, WHITE_STAINED_GLASS_PANE,
    RED_STAINED_GLASS_PANE, LIGHT_BLUE_STAINED_GLASS_PANE, GREEN_STAINED_GLASS_PANE,
    YELLOW_STAINED_GLASS_PANE, PINK_STAINED_GLASS_PANE, ORANGE_STAINED_GLASS_PANE,
    NETHER_STAR, BOOK, WRITABLE_BOOK, CLOCK, COMPASS, SUNFLOWER, LILY_OF_THE_VALLEY,
    OAK_SIGN, BARRIER, GLOWSTONE_DUST, NETHER_WART, ENDER_EYE, PAPER, ENCHANTED_BOOK,
    DIAMOND, EMERALD, GOLD_INGOT, IRON_INGOT, BONE, HONEY_BOTTLE, CAULDRON, NETHER_PORTAL, STICK, ARROW, REDSTONE, HONEYCOMB, HOPPER
}
