package org.bukkit.inventory;
public enum Material {
    AIR,
    PAPER, BOOK, DIAMOND, EMERALD, NETHER_STAR, CLOCK, COMPASS, GOLD_INGOT,
    REDSTONE, BARRIER, ENDER_EYE, NAME_TAG, BLACK_STAINED_GLASS_PANE,
    WHITE_DYE, ORANGE_DYE, MAGENTA_DYE, LIME_DYE, YELLOW_DYE, GREEN_DYE,
    CYAN_DYE, BLUE_DYE, PURPLE_DYE, WHITE_STAINED_GLASS_PANE
}
